# Source registration for the out-of-tree Goodix SPI drivers. This file is
# copied into libfprint/drivers/goodix-spi/ by install.sh.
goodix_spi_driver_sources = {
    'gdix51c0' :
        goodix_common_sources + goodix_chicago_sources + files(
            '../gdix51c0/gdix51c0.c',
            '../gdix51c0/gdix51c0-proto.c',
            '../gdix51c0/gdix51c0-tls.c',
            '../gdix51c0/gdix51c0-listener.c',
            '../gdix51c0/gdix51c0-wb.c',
        ),
}
